spring:
  datasource:
    url: jdbc:mysql://82.157.162.80:3306/luckcat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: luckcat
    password: root
    druid:
      max-active: 10 # 最大活跃数量 默认8
      min-idle: 2 # 最小空闲数 默认0
      initial-size: 5 # 初始连接数
      max-wait: 2000 # 获取连接最大等待时间 默认 -1
      validation-query: select 1
      validation-query-timeout: 5000
      time-between-eviction-runs-millis: 2000 # 间隔多久进行检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 600000 # 配置连接在池中最小生存的时间
      max-wait-thread-count: 20 # 最大等待线程数
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #基于AntPathMatcher的路径匹配

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 82.157.162.80
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # mail邮件配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 1304206691@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: cnchnwgasxndffaj
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

server:
  port: 1111
#sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: LcukCat
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: false
  # jwt秘钥
  jwt-secret-key: luckcatmingmingdongfang

minio:
  username: minioadmin
  key: minioadmin
  url: http://82.157.162.80:9000
  buckName: photo