spring:
  datasource:
    url: jdbc:mysql://82.157.162.80:3306/luckcat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: luckcat
    password: root
    druid:
      max-active: 10 # 最大活跃数量 默认8
      min-idle: 2 # 最小空闲数 默认0
      initial-size: 5 # 初始连接数
      max-wait: 2000 # 获取连接最大等待时间 默认 -1
      validation-query: select 1
      validation-query-timeout: 5000
      time-between-eviction-runs-millis: 2000 # 间隔多久进行检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 600000 # 配置连接在池中最小生存的时间
      max-wait-thread-count: 20 # 最大等待线程数
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #基于AntPathMatcher的路径匹配

server:
  port: 1111